language: java

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

cache:
  directories:
    - $HOME/.m2

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -vitamin9292@mail.ru
    on_success: never # default: change
    on_failure: always # default: always